### ISSUE TITLE
Loosen the package version constraints of dependencies

### ISSUE THREAD

**Issue by starrify** [scrapinghub/shub-workflow#3]
Currently (as of 3393bb8) this package has got [a list of dependencies](https://github.com/scrapinghub/shub-workflow/blob/3393bb8/setup.py#L14) which is in conflict to some other commonly required ones, like [those required in scrapinghub-stack-scrapy:1.6-py3](https://github.com/scrapinghub/scrapinghub-stack-scrapy/blob/branch-1.6-py3/requirements.txt).

It may be resolved by overriding dependencies from the base docker image ([example](https://bitbucket.org/scrapinghub/dod-riv-data/commits/71b208779c16548131abea55bd66330a6a50c43e)). However, it'll be good if we just loosen the constraints (if possible) here.

**Comment by kalessin** [comment]
As I can see, the only difference is in pyyaml. Did you notice another conflict?

**Comment by starrify** [comment]
As suggested in [the earlier example](https://bitbucket.org/scrapinghub/dod-riv-data/commits/71b208779c16548131abea55bd66330a6a50c43e), we've got also `botocore` and `awscli` to care about.

Sample dependency chains:
- `shub-workflow@3393bb8` -> `boto3>=1.9.92` -> `botocore<1.13.0,>=1.12.163`
- `scrapinghub-stack-scrapy@1.6-py3` -> `botocore==1.12.91`

BTW I've not yet checked any other version of `scrapinghub-stack-scrapy`.

**Comment by kalessin** [comment]
The boto3 minimal version imposed in setup.py is the required for s3fs for working correctly. I think the problem here is on scrapinghub-stack-scrapy side. They are who should loose the required version. Also, considering that botocore is constantly releasing new versions with fixes.

**Comment by starrify** [comment]
Right. Much agreed! Thanks. :)

**Comment by kalessin** [comment]
I updated the requirement string of pyyaml

https://github.com/scrapinghub/shub-workflow/commit/9111442b47ee961776e27d4d86422b6add46add5
